window.WUFC_DATA = {
  season: '2026/27',
  squad: [
    { no: 1, name: 'Johnny', pos: 'GK', status: 'Active' },
    { no: 2, name: 'Blake', pos: 'DEF', status: 'Active' },
    { no: 3, name: 'Theo', pos: 'DEF', status: 'Active' },
    { no: 4, name: 'Kane', pos: 'DEF', status: 'Active' },
    { no: 5, name: 'Freddie', pos: 'MID', status: 'Active' },
    { no: 6, name: 'Jake', pos: 'MID', status: 'Active' },
    { no: 7, name: 'Yusuf', pos: 'MID', status: 'Active' },
    { no: 8, name: 'Oliver', pos: 'MID', status: 'Active' },
    { no: 9, name: 'Charlie', pos: 'FWD', status: 'Active' },
    { no: 10, name: 'Joseph', pos: 'MID', status: 'Active' },
    { no: 11, name: 'Ollie Anderson', pos: 'DEF', status: 'Active' },
    { no: 12, name: 'Ewan', pos: 'DEF', status: 'Active' },
    { no: 15, name: 'Kyran Archbold', pos: 'MID', status: 'Active' }
  ],
  matches: [
    {
      id: 'm1',
      date: '2026-09-05',
      competition: 'League',
      venue: 'Away',
      opponent: 'Cramlington Blue Star U13 Milan',
      shortOpponent: 'Cramlington Blue Star Milan',
      gf: 4, ga: 0, htFor: 2, htAgainst: 0,
      captain: 'Freddie', potm: 'Theo', playersPlayer: 'Kane', cleanSheet: true,
      starters: ['Johnny','Blake','Kane','Theo','Freddie','Jake','Yusuf','Oliver','Charlie'],
      subs: ['Kyran Archbold','Joseph','Ewan'],
      goals: [
        { minute: 12, scorer: 'Jake', assister: '' },
        { minute: 24, scorer: 'Charlie', assister: 'Oliver' },
        { minute: 55, scorer: 'Oliver', assister: 'Charlie' },
        { minute: 60, scorer: 'Charlie', assister: 'Oliver' }
      ],
      headline: 'What a way to start.',
      next: 'Blakelaw', nextDate: '2026-09-08',
      report: [
        'Yesterday we asked a question. After finishing runners-up and earning promotion last season, could this group make the step up? A new division. Stronger opposition. More physical football. Less time on the ball. Fewer chances. We said the Silvers would need belief, positivity, courage, creativity and, above everything else, hard work. Today, they gave us the answer.',
        'An emphatic 4–0 away victory. And arguably even more pleasing than the scoreline was how they achieved it — and some of the individual signs of development we saw along the way.',
        'From the opening whistle, Westerhope looked ready. Captain Freddie led by example in the middle alongside Jake. Both were immediately into tackles, competing for everything and looking to move possession quickly into the wide areas for Yusuf and Oliver.',
        'It was a genuine captain’s performance from Freddie — disciplined, physical when required, composed on the ball and constantly working for the team. He was excellent throughout and really set the tone.',
        'Within two minutes, Theo won possession at the back, beat his man and released Oliver down the left. Oliver reached the byline and delivered for Charlie — an early warning of what was coming.',
        'A minute later, almost the same route opened again. Theo found Jake, who looked up and threaded an excellent ball between centre-back and full-back into Oliver’s path. Oliver drove into the space and delivered again, only for Cramlington to clear.',
        'The home side threatened too. Johnny was called into action early and produced a fine save to keep things level.',
        'On the right, Blake justified his starting place immediately. After his excellent attitude throughout the summer and Man of the Match performance on the final day of last season, he looked assured — making interceptions and trying to move possession positively towards Yusuf and inside to midfield.',
        'And there was one little moment that probably said more about Blake’s development than anything else. He went into a strong challenge and didn’t quite come out on top. Last season, perhaps that affects him. Perhaps there’s a little hesitation when the next one arrives. Not this time. The next challenge came along and Blake went in harder, stronger and more determined — and won it. That’s progress. It doesn’t appear on a scoresheet, but seeing a player respond differently to a situation than he might have twelve months ago is exactly what development looks like. Brilliant to see.',
        'And in the centre? Kane was having absolutely none of it. Headers won. Balls attacked before they could drop. Tackles made. Exactly what you want from your centre-back.',
        '12' | 0–1 | Jake. Oliver’s corner caused chaos. Oliver got another effort away — saved. The rebound fell to Yusuf — another excellent save. But the third one wasn’t getting away. Jake reacted quickest and buried it. Opening day. Jake goal. Again. We make that three opening-day goals in succession now. Some traditions are definitely worth keeping.',
        'The Silvers continued to play. Freddie and Jake were controlling large parts of midfield, Yusuf was providing an outlet on the right, Oliver was constantly looking to attack from the left and Charlie’s pace through the middle was giving the home defence plenty to think about.',
        'Kyran was introduced for his first competitive appearance with the team and, understandably, there were perhaps a few nerves in those opening minutes. A couple of moments didn’t quite go his way. But his head never dropped. He kept working, kept competing, kept wanting the ball, and gradually the attitude, physicality and determination we already know Kyran can bring began to shine through. For a new player coming into a new side, that’s important. Things won’t always happen immediately. It’s how you respond when they don’t. And Kyran responded brilliantly.',
        'Then came one of the best passages of football of the afternoon. Kyran moved possession into Joseph. Joseph found Jake. Westerhope recycled the ball through Freddie, Theo and Kane rather than forcing it. Eventually Jake looked up and sprayed a beautiful ball across the pitch towards Joseph on the right, whose delivery was gathered by the goalkeeper. No goal, but excellent football. Right to left. Back to front. Patient when necessary. Positive when the opportunity appeared.',
        'Then, on 24 minutes, came the second. Initially, Cramlington looked dangerous. They drove forward with numbers and suddenly Westerhope appeared exposed. Then Kane arrived with an absolute beast of a tackle. Attack over. Within seconds, defence became attack. Kyran moved the ball forward. Jake and Theo combined. Then the ball was released down the left towards Oliver.',
        'And this was another moment that showed development. Last season? Maybe that ball runs out. Today? Absolutely no chance. Up against probably the biggest player on the pitch, Oliver chased what looked like a lost cause while Cramlington’s number four attempted to shepherd it out. Oliver refused to give it up. He somehow kept it in, dragged it back and produced a brilliant piece of skill to manufacture space from absolutely nothing.',
        'Then he looked up. Charlie. The pass arrived. First touch — inside one defender. Second touch — beyond another. There was contact and Charlie could perhaps have gone down looking for a penalty. He didn’t. He stayed up. Keeper to beat. Bottom corner. 2–0. Brilliant determination from Oliver. Brilliant composure from Charlie. And exactly the sort of positivity we’d talked about before kick-off.',
        'There was something else really encouraging about Charlie’s performance too. Last season, we know there were occasions when things didn’t quite go his way and the frustration could creep in. Today there were still those moments. The ball didn’t always break for him. Defenders got in the way. Chances didn’t always arrive. But his response was different. Dust yourself off. Go again. No dwelling on the previous chance. Keep making the run. Keep causing problems. Keep believing the next opportunity is coming. Eventually he walked away with two goals. Another really important sign of development.',
        'HALF-TIME: Cramlington 0–2 Westerhope.',
        'The second half brought a different challenge. Cramlington increased the pressure and the game became more physical. For a spell, Westerhope lost some of the control Freddie and Jake had established in the first half and the home side began finding more space. This was where the Silvers needed to show another side of themselves.',
        'And Johnny stepped up. With Cramlington looking for a route back into the match, he produced an outstanding save to preserve the two-goal advantage and give everybody a chance to reset.',
        'At the other end, Johnny nearly became the creator himself. His long clearance was misjudged by the Cramlington defence and Charlie was suddenly through. Charlie brought it inside onto his right and fired towards goal… only for a defender to produce an absolutely outstanding goal-line clearance. Credit where it’s due. Superb defending.',
        'Cramlington kept coming. A slightly soft-looking free kick around the Westerhope box created another dangerous moment. Jake initially headed the ball away, it came straight back, and Kane somehow managed to get a leg in the way and divert the effort over for a corner. Again: whatever needed doing, somebody did it.',
        'Meanwhile, Ewan had initially entered on the left wing before moving into left-back when Theo came off. And that’s when he really sprang into life. Strong in the challenge. Positive in possession. He won the ball at left-back, combined with Kane and helped Westerhope begin playing through the pressure again.',
        'Then came the goal of the game.',
        '55' | 0–3 | Oliver. Westerhope worked possession through Ewan, Kane, Jake and Freddie before Charlie dropped slightly deeper to receive the ball. Oliver was already on his bike. Charlie saw him and played a beautiful ball into his path on the left.',
        'Oliver collected it with plenty still to do. One touch inside. Looked up. Left foot. From outside the box… BANG. The ball absolutely arrowed over the goalkeeper and into the far top corner.',
        'If you saw Harvey Barnes’ goal yesterday, it was basically the left-footed version from the opposite side — straight over the keeper and into the top corner. An absolute beauty.',
        'Although there is now some controversy developing after the game… because Oliver apparently claims it was a cross. 😂 We’re choosing to ignore that. We’re recording it as a shot. Definitely a shot, Oliver. The Match Report Committee has spoken. Cross or shot, though, it doesn’t really matter. Goal of the game. Absolutely brilliant.',
        'And naturally, after scoring something like that… the moonwalk celebration followed. 🕺😂',
        'At 3–0, the job looked done. Cramlington’s heads understandably dropped. But Westerhope still weren’t finished.',
        '60' | 0–4 | Charlie. Once again, the goal came from doing the basics properly first. Win possession. Keep possession. Move the opposition. Kane was involved. Kyran pushed forward down the right. Yusuf received it and played inside to Jake. Jake switched the play. Ewan got there first and found Oliver further forward. One touch from Oliver took him beyond the defender. Then the ball went through to Charlie.',
        'Step-over. Inside. Right foot. Driven over the goalkeeper. Charlie’s second. Westerhope’s fourth. And perhaps the perfect reward for a striker who had spent the afternoon refusing to become frustrated when things didn’t quite fall his way. Shortly afterwards, full-time.',
        'FULL TIME: Cramlington Blue Star U13 Milan 0–4 Westerhope United U13 Silvers.',
        'Four goals. Three points. A clean sheet. A fantastic first step into the new division.',
        'But perhaps the biggest positive wasn’t actually the score. Look a little deeper. Blake loses a challenge — and attacks the next one harder. Kyran has a nervous few minutes on his competitive debut — but his head never drops and he grows into the game. Charlie doesn’t always get the rub of the green — but instead of becoming frustrated, he keeps going and finishes with two goals. Oliver chases a ball that perhaps twelve months ago gets allowed to run out — and creates a goal from it.',
        'Those things matter. That’s confidence. That’s resilience. That’s maturity. That’s development.',
        'And when you start seeing those changes across an entire group of players, you know the work being done is beginning to make a difference.',
        'Johnny made big saves at important moments and earned a deserved clean sheet. Blake was rewarded for his summer attitude and showed another step forward in confidence. Kane was outstanding defensively and earned Players’ Player. Theo was excellent defensively and going forward and earned Player of the Match. Freddie delivered a genuine captain’s performance. Jake controlled possession, created chances and kept his opening-day scoring habit alive. Yusuf provided an outlet on the right and contributed to the build-up play. Oliver combined determination and creativity with two assists and a spectacular goal. Charlie led the line brilliantly, kept going and scored twice. Kyran overcame early nerves on debut and grew into the game. Joseph provided movement and energy. Ewan adapted brilliantly when asked to move into defence and played a part in the third goal.',
        'PLAYER OF THE MATCH — THEO. Excellent covering defensively, brave when stepping forward and those marauding runs down the left repeatedly gave the team another attacking option. Thoroughly deserved.',
        'PLAYERS’ PLAYER OF THE MATCH — KANE. A fantastic defensive display. Very little got beyond him all afternoon. But today was one of those performances where the award genuinely could have gone almost anywhere. It was a proper team performance.',
        'Thank you as always to all the parents and supporters who travelled, encouraged the boys and helped out — including those taking their turn running the line.',
        'We enjoy this one. But only briefly. Because on Tuesday… we go again.',
        'NEXT: BLAKELAW — AWAY. Another challenge. Another opportunity. Bring that same attitude. Bring that same work rate. Bring that same belief.',
        'Last season this group earned promotion. Today they showed they have absolutely no intention of simply making up the numbers at the next level. Four goals. Clean sheet. Three points. Job done.',
        'MATCH SUMMARY: FULL TIME — Cramlington Blue Star U13 Milan 0–4 Westerhope United U13 Silvers. HALF TIME — Cramlington Blue Star U13 Milan 0–2 Westerhope United U13 Silvers. GOALS — 12’ Jake (Assist: —); 24’ Charlie (Oliver); 55’ Oliver (Charlie); 60’ Charlie (Oliver). Player of the Match: Theo. Players’ Player of the Match: Kane. Clean Sheet: Johnny.',
        'UP THE HOPE! ///'
    ],
      development: [
        { player: 'Blake', text: 'Lost one physical challenge, then attacked the next one harder and won it — a clear sign of growing confidence.' },
        { player: 'Kyran Archbold', text: 'A nervy start on debut, but his head never dropped. He grew into the game and showed the attitude and physicality we know he can bring.' },
        { player: 'Charlie', text: 'Kept going when things did not fall his way and turned frustration into a two-goal performance.' },
        { player: 'Oliver', text: 'Chased down a seemingly lost ball, created the second goal and produced the goal of the game.' }
      ],
      gallery: []
    }
  ],
  leagueTableUrl: '',
  meta: { lastUpdated: '2026-09-06' }
};
